### ISSUE TITLE
I am not sure if Pkg.clone still works. Pkg.add(url=...) does though.

### ISSUE THREAD

**Issue by russelljjarvis** [paulmthompson/SpikeSorting.jl#13]
Hi @paulmthompson, great package!

## Installation
Pkg.add(url="https://github.com/paulmthompson/SpikeSorting.jl.git")
Pkg.add(url="https://github.com/paulmthompson/Spikes.jl.git")

Also I wonder if Spikes is included in SpikeSorting?

**Comment by paulmthompson** [comment]
Thank you for your interest! I have updated the Package installation command for the new Julia version.

> Also I wonder if Spikes is included in SpikeSorting?

I don't use the Spikes.jl package anymore, although SpikeSorting.jl does have a "Spike" struct.  

Let me know if you have any other questions.

**Comment by russelljjarvis** [comment]
Cheers, thanks for that! :)
